const _countries = {
  countries: {
    country: [
      {
        countryCode: 'AD',
        countryName: 'Andorra',
        currencyCode: 'EUR',
        population: '84000',
        capital: 'Andorra la Vella',
        continentName: 'Europe',
      },
      {
        countryCode: 'AE',
        countryName: 'United Arab Emirates',
        currencyCode: 'AED',
        population: '4975593',
        capital: 'Abu Dhabi',
        continentName: 'Asia',
      },
      {
        countryCode: 'AF',
        countryName: 'Afghanistan',
        currencyCode: 'AFN',
        population: '29121286',
        capital: 'Kabul',
        continentName: 'Asia',
      },
      {
        countryCode: 'AG',
        countryName: 'Antigua and Barbuda',
        currencyCode: 'XCD',
        population: '86754',
        capital: "St. John's",
        continentName: 'North America',
      },
      {
        countryCode: 'AI',
        countryName: 'Anguilla',
        currencyCode: 'XCD',
        population: '13254',
        capital: 'The Valley',
        continentName: 'North America',
      },
      {
        countryCode: 'AL',
        countryName: 'Albania',
        currencyCode: 'ALL',
        population: '2986952',
        capital: 'Tirana',
        continentName: 'Europe',
      },
      {
        countryCode: 'AM',
        countryName: 'Armenia',
        currencyCode: 'AMD',
        population: '2968000',
        capital: 'Yerevan',
        continentName: 'Asia',
      },
      {
        countryCode: 'AO',
        countryName: 'Angola',
        currencyCode: 'AOA',
        population: '13068161',
        capital: 'Luanda',
        continentName: 'Africa',
      },
      {
        countryCode: 'AQ',
        countryName: 'Antarctica',
        currencyCode: '',
        population: '0',
        capital: '',
        continentName: 'Antarctica',
      },
      {
        countryCode: 'AR',
        countryName: 'Argentina',
        currencyCode: 'ARS',
        population: '41343201',
        capital: 'Buenos Aires',
        continentName: 'South America',
      },
      {
        countryCode: 'AS',
        countryName: 'American Samoa',
        currencyCode: 'USD',
        population: '57881',
        capital: 'Pago Pago',
        continentName: 'Oceania',
      },
      {
        countryCode: 'AT',
        countryName: 'Austria',
        currencyCode: 'EUR',
        population: '8205000',
        capital: 'Vienna',
        continentName: 'Europe',
      },
      {
        countryCode: 'AU',
        countryName: 'Australia',
        currencyCode: 'AUD',
        population: '21515754',
        capital: 'Canberra',
        continentName: 'Oceania',
      },
      {
        countryCode: 'AW',
        countryName: 'Aruba',
        currencyCode: 'AWG',
        population: '71566',
        capital: 'Oranjestad',
        continentName: 'North America',
      },
      {
        countryCode: 'AX',
        countryName: 'Åland',
        currencyCode: 'EUR',
        population: '26711',
        capital: 'Mariehamn',
        continentName: 'Europe',
      },
      {
        countryCode: 'AZ',
        countryName: 'Azerbaijan',
        currencyCode: 'AZN',
        population: '8303512',
        capital: 'Baku',
        continentName: 'Asia',
      },
      {
        countryCode: 'BA',
        countryName: 'Bosnia and Herzegovina',
        currencyCode: 'BAM',
        population: '4590000',
        capital: 'Sarajevo',
        continentName: 'Europe',
      },
      {
        countryCode: 'BB',
        countryName: 'Barbados',
        currencyCode: 'BBD',
        population: '285653',
        capital: 'Bridgetown',
        continentName: 'North America',
      },
      {
        countryCode: 'BD',
        countryName: 'Bangladesh',
        currencyCode: 'BDT',
        population: '156118464',
        capital: 'Dhaka',
        continentName: 'Asia',
      },
      {
        countryCode: 'BE',
        countryName: 'Belgium',
        currencyCode: 'EUR',
        population: '10403000',
        capital: 'Brussels',
        continentName: 'Europe',
      },
      {
        countryCode: 'BF',
        countryName: 'Burkina Faso',
        currencyCode: 'XOF',
        population: '16241811',
        capital: 'Ouagadougou',
        continentName: 'Africa',
      },
      {
        countryCode: 'BG',
        countryName: 'Bulgaria',
        currencyCode: 'BGN',
        population: '7148785',
        capital: 'Sofia',
        continentName: 'Europe',
      },
      {
        countryCode: 'BH',
        countryName: 'Bahrain',
        currencyCode: 'BHD',
        population: '738004',
        capital: 'Manama',
        continentName: 'Asia',
      },
      {
        countryCode: 'BI',
        countryName: 'Burundi',
        currencyCode: 'BIF',
        population: '9863117',
        capital: 'Bujumbura',
        continentName: 'Africa',
      },
      {
        countryCode: 'BJ',
        countryName: 'Benin',
        currencyCode: 'XOF',
        population: '9056010',
        capital: 'Porto-Novo',
        continentName: 'Africa',
      },
      {
        countryCode: 'BL',
        countryName: 'Saint Barthélemy',
        currencyCode: 'EUR',
        population: '8450',
        capital: 'Gustavia',
        continentName: 'North America',
      },
      {
        countryCode: 'BM',
        countryName: 'Bermuda',
        currencyCode: 'BMD',
        population: '65365',
        capital: 'Hamilton',
        continentName: 'North America',
      },
      {
        countryCode: 'BN',
        countryName: 'Brunei',
        currencyCode: 'BND',
        population: '395027',
        capital: 'Bandar Seri Begawan',
        continentName: 'Asia',
      },
      {
        countryCode: 'BO',
        countryName: 'Bolivia',
        currencyCode: 'BOB',
        population: '9947418',
        capital: 'Sucre',
        continentName: 'South America',
      },
      {
        countryCode: 'BQ',
        countryName: 'Bonaire',
        currencyCode: 'USD',
        population: '18012',
        capital: 'Kralendijk',
        continentName: 'North America',
      },
      {
        countryCode: 'BR',
        countryName: 'Brazil',
        currencyCode: 'BRL',
        population: '201103330',
        capital: 'Brasília',
        continentName: 'South America',
      },
      {
        countryCode: 'BS',
        countryName: 'Bahamas',
        currencyCode: 'BSD',
        population: '301790',
        capital: 'Nassau',
        continentName: 'North America',
      },
      {
        countryCode: 'BT',
        countryName: 'Bhutan',
        currencyCode: 'BTN',
        population: '699847',
        capital: 'Thimphu',
        continentName: 'Asia',
      },
      {
        countryCode: 'BV',
        countryName: 'Bouvet Island',
        currencyCode: 'NOK',
        population: '0',
        capital: '',
        continentName: 'Antarctica',
      },
      {
        countryCode: 'BW',
        countryName: 'Botswana',
        currencyCode: 'BWP',
        population: '2029307',
        capital: 'Gaborone',
        continentName: 'Africa',
      },
      {
        countryCode: 'BY',
        countryName: 'Belarus',
        currencyCode: 'BYR',
        population: '9685000',
        capital: 'Minsk',
        continentName: 'Europe',
      },
      {
        countryCode: 'BZ',
        countryName: 'Belize',
        currencyCode: 'BZD',
        population: '314522',
        capital: 'Belmopan',
        continentName: 'North America',
      },
      {
        countryCode: 'CA',
        countryName: 'Canada',
        currencyCode: 'CAD',
        population: '33679000',
        capital: 'Ottawa',
        continentName: 'North America',
      },
      {
        countryCode: 'CC',
        countryName: 'Cocos [Keeling] Islands',
        currencyCode: 'AUD',
        population: '628',
        capital: 'West Island',
        continentName: 'Asia',
      },
      {
        countryCode: 'CD',
        countryName: 'Democratic Republic of the Congo',
        currencyCode: 'CDF',
        population: '70916439',
        capital: 'Kinshasa',
        continentName: 'Africa',
      },
      {
        countryCode: 'CF',
        countryName: 'Central African Republic',
        currencyCode: 'XAF',
        population: '4844927',
        capital: 'Bangui',
        continentName: 'Africa',
      },
      {
        countryCode: 'CG',
        countryName: 'Republic of the Congo',
        currencyCode: 'XAF',
        population: '3039126',
        capital: 'Brazzaville',
        continentName: 'Africa',
      },
      {
        countryCode: 'CH',
        countryName: 'Switzerland',
        currencyCode: 'CHF',
        population: '7581000',
        capital: 'Bern',
        continentName: 'Europe',
      },
      {
        countryCode: 'CI',
        countryName: 'Ivory Coast',
        currencyCode: 'XOF',
        population: '21058798',
        capital: 'Yamoussoukro',
        continentName: 'Africa',
      },
      {
        countryCode: 'CK',
        countryName: 'Cook Islands',
        currencyCode: 'NZD',
        population: '21388',
        capital: 'Avarua',
        continentName: 'Oceania',
      },
      {
        countryCode: 'CL',
        countryName: 'Chile',
        currencyCode: 'CLP',
        population: '16746491',
        capital: 'Santiago',
        continentName: 'South America',
      },
      {
        countryCode: 'CM',
        countryName: 'Cameroon',
        currencyCode: 'XAF',
        population: '19294149',
        capital: 'Yaoundé',
        continentName: 'Africa',
      },
      {
        countryCode: 'CN',
        countryName: 'China',
        currencyCode: 'CNY',
        population: '1330044000',
        capital: 'Beijing',
        continentName: 'Asia',
      },
      {
        countryCode: 'CO',
        countryName: 'Colombia',
        currencyCode: 'COP',
        population: '47790000',
        capital: 'Bogotá',
        continentName: 'South America',
      },
      {
        countryCode: 'CR',
        countryName: 'Costa Rica',
        currencyCode: 'CRC',
        population: '4516220',
        capital: 'San José',
        continentName: 'North America',
      },
      {
        countryCode: 'CU',
        countryName: 'Cuba',
        currencyCode: 'CUP',
        population: '11423000',
        capital: 'Havana',
        continentName: 'North America',
      },
      {
        countryCode: 'CV',
        countryName: 'Cape Verde',
        currencyCode: 'CVE',
        population: '508659',
        capital: 'Praia',
        continentName: 'Africa',
      },
      {
        countryCode: 'CW',
        countryName: 'Curacao',
        currencyCode: 'ANG',
        population: '141766',
        capital: 'Willemstad',
        continentName: 'North America',
      },
      {
        countryCode: 'CX',
        countryName: 'Christmas Island',
        currencyCode: 'AUD',
        population: '1500',
        capital: 'Flying Fish Cove',
        continentName: 'Asia',
      },
      {
        countryCode: 'CY',
        countryName: 'Cyprus',
        currencyCode: 'EUR',
        population: '1102677',
        capital: 'Nicosia',
        continentName: 'Europe',
      },
      {
        countryCode: 'CZ',
        countryName: 'Czechia',
        currencyCode: 'CZK',
        population: '10476000',
        capital: 'Prague',
        continentName: 'Europe',
      },
      {
        countryCode: 'DE',
        countryName: 'Germany',
        currencyCode: 'EUR',
        population: '81802257',
        capital: 'Berlin',
        continentName: 'Europe',
      },
      {
        countryCode: 'DJ',
        countryName: 'Djibouti',
        currencyCode: 'DJF',
        population: '740528',
        capital: 'Djibouti',
        continentName: 'Africa',
      },
      {
        countryCode: 'DK',
        countryName: 'Denmark',
        currencyCode: 'DKK',
        population: '5484000',
        capital: 'Copenhagen',
        continentName: 'Europe',
      },
      {
        countryCode: 'DM',
        countryName: 'Dominica',
        currencyCode: 'XCD',
        population: '72813',
        capital: 'Roseau',
        continentName: 'North America',
      },
      {
        countryCode: 'DO',
        countryName: 'Dominican Republic',
        currencyCode: 'DOP',
        population: '9823821',
        capital: 'Santo Domingo',
        continentName: 'North America',
      },
      {
        countryCode: 'DZ',
        countryName: 'Algeria',
        currencyCode: 'DZD',
        population: '34586184',
        capital: 'Algiers',
        continentName: 'Africa',
      },
      {
        countryCode: 'EC',
        countryName: 'Ecuador',
        currencyCode: 'USD',
        population: '14790608',
        capital: 'Quito',
        continentName: 'South America',
      },
      {
        countryCode: 'EE',
        countryName: 'Estonia',
        currencyCode: 'EUR',
        population: '1291170',
        capital: 'Tallinn',
        continentName: 'Europe',
      },
      {
        countryCode: 'EG',
        countryName: 'Egypt',
        currencyCode: 'EGP',
        population: '80471869',
        capital: 'Cairo',
        continentName: 'Africa',
      },
      {
        countryCode: 'EH',
        countryName: 'Western Sahara',
        currencyCode: 'MAD',
        population: '273008',
        capital: 'Laâyoune / El Aaiún',
        continentName: 'Africa',
      },
      {
        countryCode: 'ER',
        countryName: 'Eritrea',
        currencyCode: 'ERN',
        population: '5792984',
        capital: 'Asmara',
        continentName: 'Africa',
      },
      {
        countryCode: 'ES',
        countryName: 'Spain',
        currencyCode: 'EUR',
        population: '46505963',
        capital: 'Madrid',
        continentName: 'Europe',
      },
      {
        countryCode: 'ET',
        countryName: 'Ethiopia',
        currencyCode: 'ETB',
        population: '88013491',
        capital: 'Addis Ababa',
        continentName: 'Africa',
      },
      {
        countryCode: 'FI',
        countryName: 'Finland',
        currencyCode: 'EUR',
        population: '5244000',
        capital: 'Helsinki',
        continentName: 'Europe',
      },
      {
        countryCode: 'FJ',
        countryName: 'Fiji',
        currencyCode: 'FJD',
        population: '875983',
        capital: 'Suva',
        continentName: 'Oceania',
      },
      {
        countryCode: 'FK',
        countryName: 'Falkland Islands',
        currencyCode: 'FKP',
        population: '2638',
        capital: 'Stanley',
        continentName: 'South America',
      },
      {
        countryCode: 'FM',
        countryName: 'Micronesia',
        currencyCode: 'USD',
        population: '107708',
        capital: 'Palikir',
        continentName: 'Oceania',
      },
      {
        countryCode: 'FO',
        countryName: 'Faroe Islands',
        currencyCode: 'DKK',
        population: '48228',
        capital: 'Tórshavn',
        continentName: 'Europe',
      },
      {
        countryCode: 'FR',
        countryName: 'France',
        currencyCode: 'EUR',
        population: '64768389',
        capital: 'Paris',
        continentName: 'Europe',
      },
      {
        countryCode: 'GA',
        countryName: 'Gabon',
        currencyCode: 'XAF',
        population: '1545255',
        capital: 'Libreville',
        continentName: 'Africa',
      },
      {
        countryCode: 'GB',
        countryName: 'United Kingdom',
        currencyCode: 'GBP',
        population: '62348447',
        capital: 'London',
        continentName: 'Europe',
      },
      {
        countryCode: 'GD',
        countryName: 'Grenada',
        currencyCode: 'XCD',
        population: '107818',
        capital: "St. George's",
        continentName: 'North America',
      },
      {
        countryCode: 'GE',
        countryName: 'Georgia',
        currencyCode: 'GEL',
        population: '4630000',
        capital: 'Tbilisi',
        continentName: 'Asia',
      },
      {
        countryCode: 'GF',
        countryName: 'French Guiana',
        currencyCode: 'EUR',
        population: '195506',
        capital: 'Cayenne',
        continentName: 'South America',
      },
      {
        countryCode: 'GG',
        countryName: 'Guernsey',
        currencyCode: 'GBP',
        population: '65228',
        capital: 'St Peter Port',
        continentName: 'Europe',
      },
      {
        countryCode: 'GH',
        countryName: 'Ghana',
        currencyCode: 'GHS',
        population: '24339838',
        capital: 'Accra',
        continentName: 'Africa',
      },
      {
        countryCode: 'GI',
        countryName: 'Gibraltar',
        currencyCode: 'GIP',
        population: '27884',
        capital: 'Gibraltar',
        continentName: 'Europe',
      },
      {
        countryCode: 'GL',
        countryName: 'Greenland',
        currencyCode: 'DKK',
        population: '56375',
        capital: 'Nuuk',
        continentName: 'North America',
      },
      {
        countryCode: 'GM',
        countryName: 'Gambia',
        currencyCode: 'GMD',
        population: '1593256',
        capital: 'Bathurst',
        continentName: 'Africa',
      },
      {
        countryCode: 'GN',
        countryName: 'Guinea',
        currencyCode: 'GNF',
        population: '10324025',
        capital: 'Conakry',
        continentName: 'Africa',
      },
      {
        countryCode: 'GP',
        countryName: 'Guadeloupe',
        currencyCode: 'EUR',
        population: '443000',
        capital: 'Basse-Terre',
        continentName: 'North America',
      },
      {
        countryCode: 'GQ',
        countryName: 'Equatorial Guinea',
        currencyCode: 'XAF',
        population: '1014999',
        capital: 'Malabo',
        continentName: 'Africa',
      },
      {
        countryCode: 'GR',
        countryName: 'Greece',
        currencyCode: 'EUR',
        population: '11000000',
        capital: 'Athens',
        continentName: 'Europe',
      },
      {
        countryCode: 'GS',
        countryName: 'South Georgia and the South Sandwich Islands',
        currencyCode: 'GBP',
        population: '30',
        capital: 'Grytviken',
        continentName: 'Antarctica',
      },
      {
        countryCode: 'GT',
        countryName: 'Guatemala',
        currencyCode: 'GTQ',
        population: '13550440',
        capital: 'Guatemala City',
        continentName: 'North America',
      },
      {
        countryCode: 'GU',
        countryName: 'Guam',
        currencyCode: 'USD',
        population: '159358',
        capital: 'Hagåtña',
        continentName: 'Oceania',
      },
      {
        countryCode: 'GW',
        countryName: 'Guinea-Bissau',
        currencyCode: 'XOF',
        population: '1565126',
        capital: 'Bissau',
        continentName: 'Africa',
      },
      {
        countryCode: 'GY',
        countryName: 'Guyana',
        currencyCode: 'GYD',
        population: '748486',
        capital: 'Georgetown',
        continentName: 'South America',
      },
      {
        countryCode: 'HK',
        countryName: 'Hong Kong',
        currencyCode: 'HKD',
        population: '6898686',
        capital: 'Hong Kong',
        continentName: 'Asia',
      },
      {
        countryCode: 'HM',
        countryName: 'Heard Island and McDonald Islands',
        currencyCode: 'AUD',
        population: '0',
        capital: '',
        continentName: 'Antarctica',
      },
      {
        countryCode: 'HN',
        countryName: 'Honduras',
        currencyCode: 'HNL',
        population: '7989415',
        capital: 'Tegucigalpa',
        continentName: 'North America',
      },
      {
        countryCode: 'HR',
        countryName: 'Croatia',
        currencyCode: 'HRK',
        population: '4284889',
        capital: 'Zagreb',
        continentName: 'Europe',
      },
      {
        countryCode: 'HT',
        countryName: 'Haiti',
        currencyCode: 'HTG',
        population: '9648924',
        capital: 'Port-au-Prince',
        continentName: 'North America',
      },
      {
        countryCode: 'HU',
        countryName: 'Hungary',
        currencyCode: 'HUF',
        population: '9982000',
        capital: 'Budapest',
        continentName: 'Europe',
      },
      {
        countryCode: 'ID',
        countryName: 'Indonesia',
        currencyCode: 'IDR',
        population: '242968342',
        capital: 'Jakarta',
        continentName: 'Asia',
      },
      {
        countryCode: 'IE',
        countryName: 'Ireland',
        currencyCode: 'EUR',
        population: '4622917',
        capital: 'Dublin',
        continentName: 'Europe',
      },
      {
        countryCode: 'IL',
        countryName: 'Israel',
        currencyCode: 'ILS',
        population: '7353985',
        capital: '',
        continentName: 'Asia',
      },
      {
        countryCode: 'IM',
        countryName: 'Isle of Man',
        currencyCode: 'GBP',
        population: '75049',
        capital: 'Douglas',
        continentName: 'Europe',
      },
      {
        countryCode: 'IN',
        countryName: 'India',
        currencyCode: 'INR',
        population: '1173108018',
        capital: 'New Delhi',
        continentName: 'Asia',
      },
      {
        countryCode: 'IO',
        countryName: 'British Indian Ocean Territory',
        currencyCode: 'USD',
        population: '4000',
        capital: '',
        continentName: 'Asia',
      },
      {
        countryCode: 'IQ',
        countryName: 'Iraq',
        currencyCode: 'IQD',
        population: '29671605',
        capital: 'Baghdad',
        continentName: 'Asia',
      },
      {
        countryCode: 'IR',
        countryName: 'Iran',
        currencyCode: 'IRR',
        population: '76923300',
        capital: 'Tehran',
        continentName: 'Asia',
      },
      {
        countryCode: 'IS',
        countryName: 'Iceland',
        currencyCode: 'ISK',
        population: '308910',
        capital: 'Reykjavik',
        continentName: 'Europe',
      },
      {
        countryCode: 'IT',
        countryName: 'Italy',
        currencyCode: 'EUR',
        population: '60340328',
        capital: 'Rome',
        continentName: 'Europe',
      },
      {
        countryCode: 'JE',
        countryName: 'Jersey',
        currencyCode: 'GBP',
        population: '90812',
        capital: 'Saint Helier',
        continentName: 'Europe',
      },
      {
        countryCode: 'JM',
        countryName: 'Jamaica',
        currencyCode: 'JMD',
        population: '2847232',
        capital: 'Kingston',
        continentName: 'North America',
      },
      {
        countryCode: 'JO',
        countryName: 'Jordan',
        currencyCode: 'JOD',
        population: '6407085',
        capital: 'Amman',
        continentName: 'Asia',
      },
      {
        countryCode: 'JP',
        countryName: 'Japan',
        currencyCode: 'JPY',
        population: '127288000',
        capital: 'Tokyo',
        continentName: 'Asia',
      },
      {
        countryCode: 'KE',
        countryName: 'Kenya',
        currencyCode: 'KES',
        population: '40046566',
        capital: 'Nairobi',
        continentName: 'Africa',
      },
      {
        countryCode: 'KG',
        countryName: 'Kyrgyzstan',
        currencyCode: 'KGS',
        population: '5776500',
        capital: 'Bishkek',
        continentName: 'Asia',
      },
      {
        countryCode: 'KH',
        countryName: 'Cambodia',
        currencyCode: 'KHR',
        population: '14453680',
        capital: 'Phnom Penh',
        continentName: 'Asia',
      },
      {
        countryCode: 'KI',
        countryName: 'Kiribati',
        currencyCode: 'AUD',
        population: '92533',
        capital: 'Tarawa',
        continentName: 'Oceania',
      },
      {
        countryCode: 'KM',
        countryName: 'Comoros',
        currencyCode: 'KMF',
        population: '773407',
        capital: 'Moroni',
        continentName: 'Africa',
      },
      {
        countryCode: 'KN',
        countryName: 'Saint Kitts and Nevis',
        currencyCode: 'XCD',
        population: '51134',
        capital: 'Basseterre',
        continentName: 'North America',
      },
      {
        countryCode: 'KP',
        countryName: 'North Korea',
        currencyCode: 'KPW',
        population: '22912177',
        capital: 'Pyongyang',
        continentName: 'Asia',
      },
      {
        countryCode: 'KR',
        countryName: 'South Korea',
        currencyCode: 'KRW',
        population: '48422644',
        capital: 'Seoul',
        continentName: 'Asia',
      },
      {
        countryCode: 'KW',
        countryName: 'Kuwait',
        currencyCode: 'KWD',
        population: '2789132',
        capital: 'Kuwait City',
        continentName: 'Asia',
      },
      {
        countryCode: 'KY',
        countryName: 'Cayman Islands',
        currencyCode: 'KYD',
        population: '44270',
        capital: 'George Town',
        continentName: 'North America',
      },
      {
        countryCode: 'KZ',
        countryName: 'Kazakhstan',
        currencyCode: 'KZT',
        population: '15340000',
        capital: 'Astana',
        continentName: 'Asia',
      },
      {
        countryCode: 'LA',
        countryName: 'Laos',
        currencyCode: 'LAK',
        population: '6368162',
        capital: 'Vientiane',
        continentName: 'Asia',
      },
      {
        countryCode: 'LB',
        countryName: 'Lebanon',
        currencyCode: 'LBP',
        population: '4125247',
        capital: 'Beirut',
        continentName: 'Asia',
      },
      {
        countryCode: 'LC',
        countryName: 'Saint Lucia',
        currencyCode: 'XCD',
        population: '160922',
        capital: 'Castries',
        continentName: 'North America',
      },
      {
        countryCode: 'LI',
        countryName: 'Liechtenstein',
        currencyCode: 'CHF',
        population: '35000',
        capital: 'Vaduz',
        continentName: 'Europe',
      },
      {
        countryCode: 'LK',
        countryName: 'Sri Lanka',
        currencyCode: 'LKR',
        population: '21513990',
        capital: 'Colombo',
        continentName: 'Asia',
      },
      {
        countryCode: 'LR',
        countryName: 'Liberia',
        currencyCode: 'LRD',
        population: '3685076',
        capital: 'Monrovia',
        continentName: 'Africa',
      },
      {
        countryCode: 'LS',
        countryName: 'Lesotho',
        currencyCode: 'LSL',
        population: '1919552',
        capital: 'Maseru',
        continentName: 'Africa',
      },
      {
        countryCode: 'LT',
        countryName: 'Lithuania',
        currencyCode: 'EUR',
        population: '2944459',
        capital: 'Vilnius',
        continentName: 'Europe',
      },
      {
        countryCode: 'LU',
        countryName: 'Luxembourg',
        currencyCode: 'EUR',
        population: '497538',
        capital: 'Luxembourg',
        continentName: 'Europe',
      },
      {
        countryCode: 'LV',
        countryName: 'Latvia',
        currencyCode: 'EUR',
        population: '2217969',
        capital: 'Riga',
        continentName: 'Europe',
      },
      {
        countryCode: 'LY',
        countryName: 'Libya',
        currencyCode: 'LYD',
        population: '6461454',
        capital: 'Tripoli',
        continentName: 'Africa',
      },
      {
        countryCode: 'MA',
        countryName: 'Morocco',
        currencyCode: 'MAD',
        population: '33848242',
        capital: 'Rabat',
        continentName: 'Africa',
      },
      {
        countryCode: 'MC',
        countryName: 'Monaco',
        currencyCode: 'EUR',
        population: '32965',
        capital: 'Monaco',
        continentName: 'Europe',
      },
      {
        countryCode: 'MD',
        countryName: 'Moldova',
        currencyCode: 'MDL',
        population: '4324000',
        capital: 'Chişinău',
        continentName: 'Europe',
      },
      {
        countryCode: 'ME',
        countryName: 'Montenegro',
        currencyCode: 'EUR',
        population: '666730',
        capital: 'Podgorica',
        continentName: 'Europe',
      },
      {
        countryCode: 'MF',
        countryName: 'Saint Martin',
        currencyCode: 'EUR',
        population: '35925',
        capital: 'Marigot',
        continentName: 'North America',
      },
      {
        countryCode: 'MG',
        countryName: 'Madagascar',
        currencyCode: 'MGA',
        population: '21281844',
        capital: 'Antananarivo',
        continentName: 'Africa',
      },
      {
        countryCode: 'MH',
        countryName: 'Marshall Islands',
        currencyCode: 'USD',
        population: '65859',
        capital: 'Majuro',
        continentName: 'Oceania',
      },
      {
        countryCode: 'MK',
        countryName: 'Macedonia',
        currencyCode: 'MKD',
        population: '2062294',
        capital: 'Skopje',
        continentName: 'Europe',
      },
      {
        countryCode: 'ML',
        countryName: 'Mali',
        currencyCode: 'XOF',
        population: '13796354',
        capital: 'Bamako',
        continentName: 'Africa',
      },
      {
        countryCode: 'MM',
        countryName: 'Myanmar [Burma]',
        currencyCode: 'MMK',
        population: '53414374',
        capital: 'Naypyitaw',
        continentName: 'Asia',
      },
      {
        countryCode: 'MN',
        countryName: 'Mongolia',
        currencyCode: 'MNT',
        population: '3086918',
        capital: 'Ulan Bator',
        continentName: 'Asia',
      },
      {
        countryCode: 'MO',
        countryName: 'Macao',
        currencyCode: 'MOP',
        population: '449198',
        capital: 'Macao',
        continentName: 'Asia',
      },
      {
        countryCode: 'MP',
        countryName: 'Northern Mariana Islands',
        currencyCode: 'USD',
        population: '53883',
        capital: 'Saipan',
        continentName: 'Oceania',
      },
      {
        countryCode: 'MQ',
        countryName: 'Martinique',
        currencyCode: 'EUR',
        population: '432900',
        capital: 'Fort-de-France',
        continentName: 'North America',
      },
      {
        countryCode: 'MR',
        countryName: 'Mauritania',
        currencyCode: 'MRO',
        population: '3205060',
        capital: 'Nouakchott',
        continentName: 'Africa',
      },
      {
        countryCode: 'MS',
        countryName: 'Montserrat',
        currencyCode: 'XCD',
        population: '9341',
        capital: 'Plymouth',
        continentName: 'North America',
      },
      {
        countryCode: 'MT',
        countryName: 'Malta',
        currencyCode: 'EUR',
        population: '403000',
        capital: 'Valletta',
        continentName: 'Europe',
      },
      {
        countryCode: 'MU',
        countryName: 'Mauritius',
        currencyCode: 'MUR',
        population: '1294104',
        capital: 'Port Louis',
        continentName: 'Africa',
      },
      {
        countryCode: 'MV',
        countryName: 'Maldives',
        currencyCode: 'MVR',
        population: '395650',
        capital: 'Malé',
        continentName: 'Asia',
      },
      {
        countryCode: 'MW',
        countryName: 'Malawi',
        currencyCode: 'MWK',
        population: '15447500',
        capital: 'Lilongwe',
        continentName: 'Africa',
      },
      {
        countryCode: 'MX',
        countryName: 'Mexico',
        currencyCode: 'MXN',
        population: '112468855',
        capital: 'Mexico City',
        continentName: 'North America',
      },
      {
        countryCode: 'MY',
        countryName: 'Malaysia',
        currencyCode: 'MYR',
        population: '28274729',
        capital: 'Kuala Lumpur',
        continentName: 'Asia',
      },
      {
        countryCode: 'MZ',
        countryName: 'Mozambique',
        currencyCode: 'MZN',
        population: '22061451',
        capital: 'Maputo',
        continentName: 'Africa',
      },
      {
        countryCode: 'NA',
        countryName: 'Namibia',
        currencyCode: 'NAD',
        population: '2128471',
        capital: 'Windhoek',
        continentName: 'Africa',
      },
      {
        countryCode: 'NC',
        countryName: 'New Caledonia',
        currencyCode: 'XPF',
        population: '216494',
        capital: 'Noumea',
        continentName: 'Oceania',
      },
      {
        countryCode: 'NE',
        countryName: 'Niger',
        currencyCode: 'XOF',
        population: '15878271',
        capital: 'Niamey',
        continentName: 'Africa',
      },
      {
        countryCode: 'NF',
        countryName: 'Norfolk Island',
        currencyCode: 'AUD',
        population: '1828',
        capital: 'Kingston',
        continentName: 'Oceania',
      },
      {
        countryCode: 'NG',
        countryName: 'Nigeria',
        currencyCode: 'NGN',
        population: '154000000',
        capital: 'Abuja',
        continentName: 'Africa',
      },
      {
        countryCode: 'NI',
        countryName: 'Nicaragua',
        currencyCode: 'NIO',
        population: '5995928',
        capital: 'Managua',
        continentName: 'North America',
      },
      {
        countryCode: 'NL',
        countryName: 'Netherlands',
        currencyCode: 'EUR',
        population: '16645000',
        capital: 'Amsterdam',
        continentName: 'Europe',
      },
      {
        countryCode: 'NO',
        countryName: 'Norway',
        currencyCode: 'NOK',
        population: '5009150',
        capital: 'Oslo',
        continentName: 'Europe',
      },
      {
        countryCode: 'NP',
        countryName: 'Nepal',
        currencyCode: 'NPR',
        population: '28951852',
        capital: 'Kathmandu',
        continentName: 'Asia',
      },
      {
        countryCode: 'NR',
        countryName: 'Nauru',
        currencyCode: 'AUD',
        population: '10065',
        capital: 'Yaren',
        continentName: 'Oceania',
      },
      {
        countryCode: 'NU',
        countryName: 'Niue',
        currencyCode: 'NZD',
        population: '2166',
        capital: 'Alofi',
        continentName: 'Oceania',
      },
      {
        countryCode: 'NZ',
        countryName: 'New Zealand',
        currencyCode: 'NZD',
        population: '4252277',
        capital: 'Wellington',
        continentName: 'Oceania',
      },
      {
        countryCode: 'OM',
        countryName: 'Oman',
        currencyCode: 'OMR',
        population: '2967717',
        capital: 'Muscat',
        continentName: 'Asia',
      },
      {
        countryCode: 'PA',
        countryName: 'Panama',
        currencyCode: 'PAB',
        population: '3410676',
        capital: 'Panama City',
        continentName: 'North America',
      },
      {
        countryCode: 'PE',
        countryName: 'Peru',
        currencyCode: 'PEN',
        population: '29907003',
        capital: 'Lima',
        continentName: 'South America',
      },
      {
        countryCode: 'PF',
        countryName: 'French Polynesia',
        currencyCode: 'XPF',
        population: '270485',
        capital: 'Papeete',
        continentName: 'Oceania',
      },
      {
        countryCode: 'PG',
        countryName: 'Papua New Guinea',
        currencyCode: 'PGK',
        population: '6064515',
        capital: 'Port Moresby',
        continentName: 'Oceania',
      },
      {
        countryCode: 'PH',
        countryName: 'Philippines',
        currencyCode: 'PHP',
        population: '99900177',
        capital: 'Manila',
        continentName: 'Asia',
      },
      {
        countryCode: 'PK',
        countryName: 'Pakistan',
        currencyCode: 'PKR',
        population: '184404791',
        capital: 'Islamabad',
        continentName: 'Asia',
      },
      {
        countryCode: 'PL',
        countryName: 'Poland',
        currencyCode: 'PLN',
        population: '38500000',
        capital: 'Warsaw',
        continentName: 'Europe',
      },
      {
        countryCode: 'PM',
        countryName: 'Saint Pierre and Miquelon',
        currencyCode: 'EUR',
        population: '7012',
        capital: 'Saint-Pierre',
        continentName: 'North America',
      },
      {
        countryCode: 'PN',
        countryName: 'Pitcairn Islands',
        currencyCode: 'NZD',
        population: '46',
        capital: 'Adamstown',
        continentName: 'Oceania',
      },
      {
        countryCode: 'PR',
        countryName: 'Puerto Rico',
        currencyCode: 'USD',
        population: '3916632',
        capital: 'San Juan',
        continentName: 'North America',
      },
      {
        countryCode: 'PS',
        countryName: 'Palestine',
        currencyCode: 'ILS',
        population: '3800000',
        capital: '',
        continentName: 'Asia',
      },
      {
        countryCode: 'PT',
        countryName: 'Portugal',
        currencyCode: 'EUR',
        population: '10676000',
        capital: 'Lisbon',
        continentName: 'Europe',
      },
      {
        countryCode: 'PW',
        countryName: 'Palau',
        currencyCode: 'USD',
        population: '19907',
        capital: 'Melekeok',
        continentName: 'Oceania',
      },
      {
        countryCode: 'PY',
        countryName: 'Paraguay',
        currencyCode: 'PYG',
        population: '6375830',
        capital: 'Asunción',
        continentName: 'South America',
      },
      {
        countryCode: 'QA',
        countryName: 'Qatar',
        currencyCode: 'QAR',
        population: '840926',
        capital: 'Doha',
        continentName: 'Asia',
      },
      {
        countryCode: 'RE',
        countryName: 'Réunion',
        currencyCode: 'EUR',
        population: '776948',
        capital: 'Saint-Denis',
        continentName: 'Africa',
      },
      {
        countryCode: 'RO',
        countryName: 'Romania',
        currencyCode: 'RON',
        population: '21959278',
        capital: 'Bucharest',
        continentName: 'Europe',
      },
      {
        countryCode: 'RS',
        countryName: 'Serbia',
        currencyCode: 'RSD',
        population: '7344847',
        capital: 'Belgrade',
        continentName: 'Europe',
      },
      {
        countryCode: 'RU',
        countryName: 'Russia',
        currencyCode: 'RUB',
        population: '140702000',
        capital: 'Moscow',
        continentName: 'Europe',
      },
      {
        countryCode: 'RW',
        countryName: 'Rwanda',
        currencyCode: 'RWF',
        population: '11055976',
        capital: 'Kigali',
        continentName: 'Africa',
      },
      {
        countryCode: 'SA',
        countryName: 'Saudi Arabia',
        currencyCode: 'SAR',
        population: '25731776',
        capital: 'Riyadh',
        continentName: 'Asia',
      },
      {
        countryCode: 'SB',
        countryName: 'Solomon Islands',
        currencyCode: 'SBD',
        population: '559198',
        capital: 'Honiara',
        continentName: 'Oceania',
      },
      {
        countryCode: 'SC',
        countryName: 'Seychelles',
        currencyCode: 'SCR',
        population: '88340',
        capital: 'Victoria',
        continentName: 'Africa',
      },
      {
        countryCode: 'SD',
        countryName: 'Sudan',
        currencyCode: 'SDG',
        population: '35000000',
        capital: 'Khartoum',
        continentName: 'Africa',
      },
      {
        countryCode: 'SE',
        countryName: 'Sweden',
        currencyCode: 'SEK',
        population: '9828655',
        capital: 'Stockholm',
        continentName: 'Europe',
      },
      {
        countryCode: 'SG',
        countryName: 'Singapore',
        currencyCode: 'SGD',
        population: '4701069',
        capital: 'Singapore',
        continentName: 'Asia',
      },
      {
        countryCode: 'SH',
        countryName: 'Saint Helena',
        currencyCode: 'SHP',
        population: '7460',
        capital: 'Jamestown',
        continentName: 'Africa',
      },
      {
        countryCode: 'SI',
        countryName: 'Slovenia',
        currencyCode: 'EUR',
        population: '2007000',
        capital: 'Ljubljana',
        continentName: 'Europe',
      },
      {
        countryCode: 'SJ',
        countryName: 'Svalbard and Jan Mayen',
        currencyCode: 'NOK',
        population: '2550',
        capital: 'Longyearbyen',
        continentName: 'Europe',
      },
      {
        countryCode: 'SK',
        countryName: 'Slovakia',
        currencyCode: 'EUR',
        population: '5455000',
        capital: 'Bratislava',
        continentName: 'Europe',
      },
      {
        countryCode: 'SL',
        countryName: 'Sierra Leone',
        currencyCode: 'SLL',
        population: '5245695',
        capital: 'Freetown',
        continentName: 'Africa',
      },
      {
        countryCode: 'SM',
        countryName: 'San Marino',
        currencyCode: 'EUR',
        population: '31477',
        capital: 'San Marino',
        continentName: 'Europe',
      },
      {
        countryCode: 'SN',
        countryName: 'Senegal',
        currencyCode: 'XOF',
        population: '12323252',
        capital: 'Dakar',
        continentName: 'Africa',
      },
      {
        countryCode: 'SO',
        countryName: 'Somalia',
        currencyCode: 'SOS',
        population: '10112453',
        capital: 'Mogadishu',
        continentName: 'Africa',
      },
      {
        countryCode: 'SR',
        countryName: 'Suriname',
        currencyCode: 'SRD',
        population: '492829',
        capital: 'Paramaribo',
        continentName: 'South America',
      },
      {
        countryCode: 'SS',
        countryName: 'South Sudan',
        currencyCode: 'SSP',
        population: '8260490',
        capital: 'Juba',
        continentName: 'Africa',
      },
      {
        countryCode: 'ST',
        countryName: 'São Tomé and Príncipe',
        currencyCode: 'STD',
        population: '175808',
        capital: 'São Tomé',
        continentName: 'Africa',
      },
      {
        countryCode: 'SV',
        countryName: 'El Salvador',
        currencyCode: 'USD',
        population: '6052064',
        capital: 'San Salvador',
        continentName: 'North America',
      },
      {
        countryCode: 'SX',
        countryName: 'Sint Maarten',
        currencyCode: 'ANG',
        population: '37429',
        capital: 'Philipsburg',
        continentName: 'North America',
      },
      {
        countryCode: 'SY',
        countryName: 'Syria',
        currencyCode: 'SYP',
        population: '22198110',
        capital: 'Damascus',
        continentName: 'Asia',
      },
      {
        countryCode: 'SZ',
        countryName: 'Swaziland',
        currencyCode: 'SZL',
        population: '1354051',
        capital: 'Mbabane',
        continentName: 'Africa',
      },
      {
        countryCode: 'TC',
        countryName: 'Turks and Caicos Islands',
        currencyCode: 'USD',
        population: '20556',
        capital: 'Cockburn Town',
        continentName: 'North America',
      },
      {
        countryCode: 'TD',
        countryName: 'Chad',
        currencyCode: 'XAF',
        population: '10543464',
        capital: "N'Djamena",
        continentName: 'Africa',
      },
      {
        countryCode: 'TF',
        countryName: 'French Southern Territories',
        currencyCode: 'EUR',
        population: '140',
        capital: 'Port-aux-Français',
        continentName: 'Antarctica',
      },
      {
        countryCode: 'TG',
        countryName: 'Togo',
        currencyCode: 'XOF',
        population: '6587239',
        capital: 'Lomé',
        continentName: 'Africa',
      },
      {
        countryCode: 'TH',
        countryName: 'Thailand',
        currencyCode: 'THB',
        population: '67089500',
        capital: 'Bangkok',
        continentName: 'Asia',
      },
      {
        countryCode: 'TJ',
        countryName: 'Tajikistan',
        currencyCode: 'TJS',
        population: '7487489',
        capital: 'Dushanbe',
        continentName: 'Asia',
      },
      {
        countryCode: 'TK',
        countryName: 'Tokelau',
        currencyCode: 'NZD',
        population: '1466',
        capital: '',
        continentName: 'Oceania',
      },
      {
        countryCode: 'TL',
        countryName: 'East Timor',
        currencyCode: 'USD',
        population: '1154625',
        capital: 'Dili',
        continentName: 'Oceania',
      },
      {
        countryCode: 'TM',
        countryName: 'Turkmenistan',
        currencyCode: 'TMT',
        population: '4940916',
        capital: 'Ashgabat',
        continentName: 'Asia',
      },
      {
        countryCode: 'TN',
        countryName: 'Tunisia',
        currencyCode: 'TND',
        population: '10589025',
        capital: 'Tunis',
        continentName: 'Africa',
      },
      {
        countryCode: 'TO',
        countryName: 'Tonga',
        currencyCode: 'TOP',
        population: '122580',
        capital: "Nuku'alofa",
        continentName: 'Oceania',
      },
      {
        countryCode: 'TR',
        countryName: 'Turkey',
        currencyCode: 'TRY',
        population: '77804122',
        capital: 'Ankara',
        continentName: 'Asia',
      },
      {
        countryCode: 'TT',
        countryName: 'Trinidad and Tobago',
        currencyCode: 'TTD',
        population: '1228691',
        capital: 'Port of Spain',
        continentName: 'North America',
      },
      {
        countryCode: 'TV',
        countryName: 'Tuvalu',
        currencyCode: 'AUD',
        population: '10472',
        capital: 'Funafuti',
        continentName: 'Oceania',
      },
      {
        countryCode: 'TW',
        countryName: 'Taiwan',
        currencyCode: 'TWD',
        population: '22894384',
        capital: 'Taipei',
        continentName: 'Asia',
      },
      {
        countryCode: 'TZ',
        countryName: 'Tanzania',
        currencyCode: 'TZS',
        population: '41892895',
        capital: 'Dodoma',
        continentName: 'Africa',
      },
      {
        countryCode: 'UA',
        countryName: 'Ukraine',
        currencyCode: 'UAH',
        population: '45415596',
        capital: 'Kiev',
        continentName: 'Europe',
      },
      {
        countryCode: 'UG',
        countryName: 'Uganda',
        currencyCode: 'UGX',
        population: '33398682',
        capital: 'Kampala',
        continentName: 'Africa',
      },
      {
        countryCode: 'UM',
        countryName: 'U.S. Minor Outlying Islands',
        currencyCode: 'USD',
        population: '0',
        capital: '',
        continentName: 'Oceania',
      },
      {
        countryCode: 'US',
        countryName: 'United States',
        currencyCode: 'USD',
        population: '310232863',
        capital: 'Washington',
        continentName: 'North America',
      },
      {
        countryCode: 'UY',
        countryName: 'Uruguay',
        currencyCode: 'UYU',
        population: '3477000',
        capital: 'Montevideo',
        continentName: 'South America',
      },
      {
        countryCode: 'UZ',
        countryName: 'Uzbekistan',
        currencyCode: 'UZS',
        population: '27865738',
        capital: 'Tashkent',
        continentName: 'Asia',
      },
      {
        countryCode: 'VA',
        countryName: 'Vatican City',
        currencyCode: 'EUR',
        population: '921',
        capital: 'Vatican City',
        continentName: 'Europe',
      },
      {
        countryCode: 'VC',
        countryName: 'Saint Vincent and the Grenadines',
        currencyCode: 'XCD',
        population: '104217',
        capital: 'Kingstown',
        continentName: 'North America',
      },
      {
        countryCode: 'VE',
        countryName: 'Venezuela',
        currencyCode: 'VEF',
        population: '27223228',
        capital: 'Caracas',
        continentName: 'South America',
      },
      {
        countryCode: 'VG',
        countryName: 'British Virgin Islands',
        currencyCode: 'USD',
        population: '21730',
        capital: 'Road Town',
        continentName: 'North America',
      },
      {
        countryCode: 'VI',
        countryName: 'U.S. Virgin Islands',
        currencyCode: 'USD',
        population: '108708',
        capital: 'Charlotte Amalie',
        continentName: 'North America',
      },
      {
        countryCode: 'VN',
        countryName: 'Vietnam',
        currencyCode: 'VND',
        population: '89571130',
        capital: 'Hanoi',
        continentName: 'Asia',
      },
      {
        countryCode: 'VU',
        countryName: 'Vanuatu',
        currencyCode: 'VUV',
        population: '221552',
        capital: 'Port Vila',
        continentName: 'Oceania',
      },
      {
        countryCode: 'WF',
        countryName: 'Wallis and Futuna',
        currencyCode: 'XPF',
        population: '16025',
        capital: 'Mata-Utu',
        continentName: 'Oceania',
      },
      {
        countryCode: 'WS',
        countryName: 'Samoa',
        currencyCode: 'WST',
        population: '192001',
        capital: 'Apia',
        continentName: 'Oceania',
      },
      {
        countryCode: 'XK',
        countryName: 'Kosovo',
        currencyCode: 'EUR',
        population: '1800000',
        capital: 'Pristina',
        continentName: 'Europe',
      },
      {
        countryCode: 'YE',
        countryName: 'Yemen',
        currencyCode: 'YER',
        population: '23495361',
        capital: 'Sanaa',
        continentName: 'Asia',
      },
      {
        countryCode: 'YT',
        countryName: 'Mayotte',
        currencyCode: 'EUR',
        population: '159042',
        capital: 'Mamoudzou',
        continentName: 'Africa',
      },
      {
        countryCode: 'ZA',
        countryName: 'South Africa',
        currencyCode: 'ZAR',
        population: '49000000',
        capital: 'Pretoria',
        continentName: 'Africa',
      },
      {
        countryCode: 'ZM',
        countryName: 'Zambia',
        currencyCode: 'ZMW',
        population: '13460305',
        capital: 'Lusaka',
        continentName: 'Africa',
      },
      {
        countryCode: 'ZW',
        countryName: 'Zimbabwe',
        currencyCode: 'ZWL',
        population: '13061000',
        capital: 'Harare',
        continentName: 'Africa',
      },
    ],
  },
};

const symbolCurrency = [
  {
    currency: 'Albania Lek',
    abbreviation: 'ALL',
    symbol: '&#76;&#101;&#107;',
  },
  {
    currency: 'Afghanistan Afghani',
    abbreviation: 'AFN',
    symbol: '&#1547;',
  },
  {
    currency: 'Argentina Peso',
    abbreviation: 'ARS',
    symbol: '&#36;',
  },
  {
    currency: 'Aruba Guilder',
    abbreviation: 'AWG',
    symbol: '&#402;',
  },
  {
    currency: 'Australia Dollar',
    abbreviation: 'AUD',
    symbol: '&#36;',
  },
  {
    currency: 'Azerbaijan New Manat',
    abbreviation: 'AZN',
    symbol: '&#1084;&#1072;&#1085;',
  },
  {
    currency: 'Bahamas Dollar',
    abbreviation: 'BSD',
    symbol: '&#36;',
  },
  {
    currency: 'Barbados Dollar',
    abbreviation: 'BBD',
    symbol: '&#36;',
  },
  {
    currency: 'Belarus Ruble',
    abbreviation: 'BYR',
    symbol: '&#112;&#46;',
  },
  {
    currency: 'Belize Dollar',
    abbreviation: 'BZD',
    symbol: '&#66;&#90;&#36;',
  },
  {
    currency: 'Bermuda Dollar',
    abbreviation: 'BMD',
    symbol: '&#36;',
  },
  {
    currency: 'Bolivia Boliviano',
    abbreviation: 'BOB',
    symbol: '&#36;&#98;',
  },
  {
    currency: 'Bosnia and Herzegovina Convertible Marka',
    abbreviation: 'BAM',
    symbol: '&#75;&#77;',
  },
  {
    currency: 'Botswana Pula',
    abbreviation: 'BWP',
    symbol: '&#80;',
  },
  {
    currency: 'Bulgaria Lev',
    abbreviation: 'BGN',
    symbol: '&#1083;&#1074;',
  },
  {
    currency: 'Brazil Real',
    abbreviation: 'BRL',
    symbol: '&#82;&#36;',
  },
  {
    currency: 'Brunei Darussalam Dollar',
    abbreviation: 'BND',
    symbol: '&#36;',
  },
  {
    currency: 'Cambodia Riel',
    abbreviation: 'KHR',
    symbol: '&#6107;',
  },
  {
    currency: 'Canada Dollar',
    abbreviation: 'CAD',
    symbol: '&#36;',
  },
  {
    currency: 'Cayman Islands Dollar',
    abbreviation: 'KYD',
    symbol: '&#36;',
  },
  {
    currency: 'Chile Peso',
    abbreviation: 'CLP',
    symbol: '&#36;',
  },
  {
    currency: 'China Yuan Renminbi',
    abbreviation: 'CNY',
    symbol: '&#165;',
  },
  {
    currency: 'Colombia Peso',
    abbreviation: 'COP',
    symbol: '&#36;',
  },
  {
    currency: 'Costa Rica Colon',
    abbreviation: 'CRC',
    symbol: '&#8353;',
  },
  {
    currency: 'Croatia Kuna',
    abbreviation: 'HRK',
    symbol: '&#107;&#110;',
  },
  {
    currency: 'Cuba Peso',
    abbreviation: 'CUP',
    symbol: '&#8369;',
  },
  {
    currency: 'Czech Republic Koruna',
    abbreviation: 'CZK',
    symbol: '&#75;&#269;',
  },
  {
    currency: 'Denmark Krone',
    abbreviation: 'DKK',
    symbol: '&#107;&#114;',
  },
  {
    currency: 'Dominican Republic Peso',
    abbreviation: 'DOP',
    symbol: '&#82;&#68;&#36;',
  },
  {
    currency: 'East Caribbean Dollar',
    abbreviation: 'XCD',
    symbol: '&#36;',
  },
  {
    currency: 'Egypt Pound',
    abbreviation: 'EGP',
    symbol: '&#163;',
  },
  {
    currency: 'El Salvador Colon',
    abbreviation: 'SVC',
    symbol: '&#36;',
  },
  {
    currency: 'Estonia Kroon',
    abbreviation: 'EEK',
    symbol: '&#107;&#114;',
  },
  {
    currency: 'Euro Member Countries',
    abbreviation: 'EUR',
    symbol: '&#8364;',
  },
  {
    currency: 'Falkland Islands (Malvinas) Pound',
    abbreviation: 'FKP',
    symbol: '&#163;',
  },
  {
    currency: 'Fiji Dollar',
    abbreviation: 'FJD',
    symbol: '&#36;',
  },
  {
    currency: 'Ghana Cedis',
    abbreviation: 'GHC',
    symbol: '&#162;',
  },
  {
    currency: 'Gibraltar Pound',
    abbreviation: 'GIP',
    symbol: '&#163;',
  },
  {
    currency: 'Guatemala Quetzal',
    abbreviation: 'GTQ',
    symbol: '&#81;',
  },
  {
    currency: 'Guernsey Pound',
    abbreviation: 'GGP',
    symbol: '&#163;',
  },
  {
    currency: 'Guyana Dollar',
    abbreviation: 'GYD',
    symbol: '&#36;',
  },
  {
    currency: 'Honduras Lempira',
    abbreviation: 'HNL',
    symbol: '&#76;',
  },
  {
    currency: 'Hong Kong Dollar',
    abbreviation: 'HKD',
    symbol: '&#36;',
  },
  {
    currency: 'Hungary Forint',
    abbreviation: 'HUF',
    symbol: '&#70;&#116;',
  },
  {
    currency: 'Iceland Krona',
    abbreviation: 'ISK',
    symbol: '&#107;&#114;',
  },
  {
    currency: 'India Rupee',
    abbreviation: 'INR',
    symbol: null,
  },
  {
    currency: 'Indonesia Rupiah',
    abbreviation: 'IDR',
    symbol: '&#82;&#112;',
  },
  {
    currency: 'Iran Rial',
    abbreviation: 'IRR',
    symbol: '&#65020;',
  },
  {
    currency: 'Isle of Man Pound',
    abbreviation: 'IMP',
    symbol: '&#163;',
  },
  {
    currency: 'Israel Shekel',
    abbreviation: 'ILS',
    symbol: '&#8362;',
  },
  {
    currency: 'Jamaica Dollar',
    abbreviation: 'JMD',
    symbol: '&#74;&#36;',
  },
  {
    currency: 'Japan Yen',
    abbreviation: 'JPY',
    symbol: '&#165;',
  },
  {
    currency: 'Jersey Pound',
    abbreviation: 'JEP',
    symbol: '&#163;',
  },
  {
    currency: 'Kazakhstan Tenge',
    abbreviation: 'KZT',
    symbol: '&#1083;&#1074;',
  },
  {
    currency: 'Korea (North) Won',
    abbreviation: 'KPW',
    symbol: '&#8361;',
  },
  {
    currency: 'Korea (South) Won',
    abbreviation: 'KRW',
    symbol: '&#8361;',
  },
  {
    currency: 'Kyrgyzstan Som',
    abbreviation: 'KGS',
    symbol: '&#1083;&#1074;',
  },
  {
    currency: 'Laos Kip',
    abbreviation: 'LAK',
    symbol: '&#8365;',
  },
  {
    currency: 'Latvia Lat',
    abbreviation: 'LVL',
    symbol: '&#76;&#115;',
  },
  {
    currency: 'Lebanon Pound',
    abbreviation: 'LBP',
    symbol: '&#163;',
  },
  {
    currency: 'Liberia Dollar',
    abbreviation: 'LRD',
    symbol: '&#36;',
  },
  {
    currency: 'Lithuania Litas',
    abbreviation: 'LTL',
    symbol: '&#76;&#116;',
  },
  {
    currency: 'Macedonia Denar',
    abbreviation: 'MKD',
    symbol: '&#1076;&#1077;&#1085;',
  },
  {
    currency: 'Malaysia Ringgit',
    abbreviation: 'MYR',
    symbol: '&#82;&#77;',
  },
  {
    currency: 'Mauritius Rupee',
    abbreviation: 'MUR',
    symbol: '&#8360;',
  },
  {
    currency: 'Mexico Peso',
    abbreviation: 'MXN',
    symbol: '&#36;',
  },
  {
    currency: 'Mongolia Tughrik',
    abbreviation: 'MNT',
    symbol: '&#8366;',
  },
  {
    currency: 'Mozambique Metical',
    abbreviation: 'MZN',
    symbol: '&#77;&#84;',
  },
  {
    currency: 'Namibia Dollar',
    abbreviation: 'NAD',
    symbol: '&#36;',
  },
  {
    currency: 'Nepal Rupee',
    abbreviation: 'NPR',
    symbol: '&#8360;',
  },
  {
    currency: 'Netherlands Antilles Guilder',
    abbreviation: 'ANG',
    symbol: '&#402;',
  },
  {
    currency: 'New Zealand Dollar',
    abbreviation: 'NZD',
    symbol: '&#36;',
  },
  {
    currency: 'Nicaragua Cordoba',
    abbreviation: 'NIO',
    symbol: '&#67;&#36;',
  },
  {
    currency: 'Nigeria Naira',
    abbreviation: 'NGN',
    symbol: '&#8358;',
  },
  {
    currency: 'Korea (North) Won',
    abbreviation: 'KPW',
    symbol: '&#8361;',
  },
  {
    currency: 'Norway Krone',
    abbreviation: 'NOK',
    symbol: '&#107;&#114;',
  },
  {
    currency: 'Oman Rial',
    abbreviation: 'OMR',
    symbol: '&#65020;',
  },
  {
    currency: 'Pakistan Rupee',
    abbreviation: 'PKR',
    symbol: '&#8360;',
  },
  {
    currency: 'Panama Balboa',
    abbreviation: 'PAB',
    symbol: '&#66;&#47;&#46;',
  },
  {
    currency: 'Paraguay Guarani',
    abbreviation: 'PYG',
    symbol: '&#71;&#115;',
  },
  {
    currency: 'Peru Nuevo Sol',
    abbreviation: 'PEN',
    symbol: '&#83;&#47;&#46;',
  },
  {
    currency: 'Philippines Peso',
    abbreviation: 'PHP',
    symbol: '&#8369;',
  },
  {
    currency: 'Poland Zloty',
    abbreviation: 'PLN',
    symbol: '&#122;&#322;',
  },
  {
    currency: 'Qatar Riyal',
    abbreviation: 'QAR',
    symbol: '&#65020;',
  },
  {
    currency: 'Romania New Leu',
    abbreviation: 'RON',
    symbol: '&#108;&#101;&#105;',
  },
  {
    currency: 'Russia Ruble',
    abbreviation: 'RUB',
    symbol: '&#1088;&#1091;&#1073;',
  },
  {
    currency: 'Saint Helena Pound',
    abbreviation: 'SHP',
    symbol: '&#163;',
  },
  {
    currency: 'Saudi Arabia Riyal',
    abbreviation: 'SAR',
    symbol: '&#65020;',
  },
  {
    currency: 'Serbia Dinar',
    abbreviation: 'RSD',
    symbol: '&#1044;&#1080;&#1085;&#46;',
  },
  {
    currency: 'Seychelles Rupee',
    abbreviation: 'SCR',
    symbol: '&#8360;',
  },
  {
    currency: 'Singapore Dollar',
    abbreviation: 'SGD',
    symbol: '&#36;',
  },
  {
    currency: 'Solomon Islands Dollar',
    abbreviation: 'SBD',
    symbol: '&#36;',
  },
  {
    currency: 'Somalia Shilling',
    abbreviation: 'SOS',
    symbol: '&#83;',
  },
  {
    currency: 'South Africa Rand',
    abbreviation: 'ZAR',
    symbol: '&#82;',
  },
  {
    currency: 'Korea (South) Won',
    abbreviation: 'KRW',
    symbol: '&#8361;',
  },
  {
    currency: 'Sri Lanka Rupee',
    abbreviation: 'LKR',
    symbol: '&#8360;',
  },
  {
    currency: 'Sweden Krona',
    abbreviation: 'SEK',
    symbol: '&#107;&#114;',
  },
  {
    currency: 'Switzerland Franc',
    abbreviation: 'CHF',
    symbol: '&#67;&#72;&#70;',
  },
  {
    currency: 'Suriname Dollar',
    abbreviation: 'SRD',
    symbol: '&#36;',
  },
  {
    currency: 'Syria Pound',
    abbreviation: 'SYP',
    symbol: '&#163;',
  },
  {
    currency: 'Taiwan New Dollar',
    abbreviation: 'TWD',
    symbol: '&#78;&#84;&#36;',
  },
  {
    currency: 'Thailand Baht',
    abbreviation: 'THB',
    symbol: '&#3647;',
  },
  {
    currency: 'Trinidad and Tobago Dollar',
    abbreviation: 'TTD',
    symbol: '&#84;&#84;&#36;',
  },
  {
    currency: 'Turkey Lira',
    abbreviation: 'TRY',
    symbol: null,
  },
  {
    currency: 'Turkey Lira',
    abbreviation: 'TRL',
    symbol: '&#8356;',
  },
  {
    currency: 'Tuvalu Dollar',
    abbreviation: 'TVD',
    symbol: '&#36;',
  },
  {
    currency: 'Ukraine Hryvna',
    abbreviation: 'UAH',
    symbol: '&#8372;',
  },
  {
    currency: 'United Kingdom Pound',
    abbreviation: 'GBP',
    symbol: '&#163;',
  },
  {
    currency: 'United States Dollar',
    abbreviation: 'USD',
    symbol: '&#36;',
  },
  {
    currency: 'Uruguay Peso',
    abbreviation: 'UYU',
    symbol: '&#36;&#85;',
  },
  {
    currency: 'Uzbekistan Som',
    abbreviation: 'UZS',
    symbol: '&#1083;&#1074;',
  },
  {
    currency: 'Venezuela Bolivar',
    abbreviation: 'VEF',
    symbol: '&#66;&#115;',
  },
  {
    currency: 'Viet Nam Dong',
    abbreviation: 'VND',
    symbol: '&#8363;',
  },
  {
    currency: 'Yemen Rial',
    abbreviation: 'YER',
    symbol: '&#65020;',
  },
  {
    currency: 'Zimbabwe Dollar',
    abbreviation: 'ZWD',
    symbol: '&#90;&#36;',
  },
];
const EXCHANGE = {
  getExchangeRate: {
    AED: 3.939211,
    AFN: 93.83968,
    ALL: 110.479678,
    AMD: 413.516505,
    ANG: 1.932418,
    AOA: 585.013521,
    ARS: 252.793077,
    AUD: 1.648472,
    AWG: 1.931095,
    AZN: 1.823895,
    BAM: 1.955892,
    BBD: 2.145642,
    BDT: 114.942802,
    BGN: 1.955041,
    BHD: 0.404628,
    BIF: 3024.240636,
    BMD: 1.072919,
    BND: 1.446773,
    BOB: 7.409702,
    BRL: 5.402392,
    BSD: 1.073331,
    BTC: 0.000041,
    BTN: 88.687122,
    BWP: 14.628048,
    BYN: 2.706278,
    BZD: 2.161438,
    CAD: 1.462691,
    CDF: 2492.877369,
    CHF: 0.97191,
    CLF: 0.031664,
    CLP: 868.66462,
    CNH: 7.607257,
    CNY: 7.592823,
    COP: 4764.994285,
    CRC: 575.608476,
    CUC: 1.072763,
    CUP: 27.615594,
    CVE: 110.253441,
    CZK: 23.610179,
    DJF: 190.854152,
    DKK: 7.447593,
    DOP: 58.585771,
    DZD: 146.680729,
    EGP: 33.138537,
    ERN: 16.087538,
    ETB: 58.415754,
    EUR: 1,
    FJD: 2.412682,
    FKP: 0.87159,
    GBP: 0.871242,
    GEL: 2.767194,
    GGP: 0.87137,
    GHS: 11.796621,
    GIP: 0.871575,
    GMD: 63.864124,
    GNF: 9242.010803,
    GTQ: 8.36834,
    GYD: 226.752769,
    HKD: 8.401051,
    HNL: 26.436961,
    HRK: 7.532579,
    HTG: 151.703977,
    HUF: 372.950326,
    IDR: 16055.519768,
    ILS: 3.999815,
    IMP: 0.87124,
    INR: 88.734064,
    IQD: 1404.627253,
    IRR: 45363.989179,
    ISK: 150.05606,
    JEP: 0.871623,
    JMD: 165.285159,
    JOD: 0.761624,
    JPY: 150.212588,
    KES: 147.720923,
    KGS: 93.860185,
    KHR: 4406.842232,
    KMF: 491.121826,
    KPW: 965.192535,
    KRW: 1426.857538,
    KWD: 0.330838,
    KYD: 0.893946,
    KZT: 478.215204,
    LAK: 18914.639775,
    LBP: 16149.831764,
    LKR: 324.203688,
    LRD: 179.955186,
    LSL: 20.685127,
    LYD: 5.159868,
    MAD: 10.983011,
    MDL: 19.059119,
    MGA: 4717.137994,
    MKD: 61.609052,
    MMK: 2251.460196,
    MNT: 3773.89798,
    MOP: 8.650515,
    MRU: 36.81039,
    MUR: 48.796825,
    MVR: 16.472988,
    MWK: 1099.304584,
    MXN: 19.146276,
    MYR: 4.960698,
    MZN: 68.528932,
    NAD: 20.64429,
    NGN: 494.353045,
    NIO: 39.185842,
    NOK: 11.851116,
    NPR: 141.898742,
    NZD: 1.768585,
    OMR: 0.413136,
    PAB: 1.072888,
    PEN: 3.951937,
    PGK: 3.79324,
    PHP: 60.157669,
    PKR: 306.403702,
    PLN: 4.502641,
    PYG: 7760.781163,
    QAR: 3.90464,
    RON: 4.950569,
    RSD: 117.199394,
    RUB: 85.820503,
    RWF: 1209.305881,
    SAR: 4.022256,
    SBD: 8.930919,
    SCR: 14.077277,
    SDG: 643.997191,
    SEK: 11.59458,
    SGD: 1.453272,
    SHP: 0.871,
    SLL: 18944.558936,
    SOS: 610.000059,
    SRD: 40.001623,
    SSP: 139.695582,
    STD: 24477.240522,
    STN: 24.801143,
    SVC: 9.380618,
    SYP: 2694.525584,
    SZL: 20.697588,
    THB: 37.234248,
    TJS: 11.708332,
    TMT: 3.7544,
    TND: 3.315189,
    TOP: 2.547772,
    TRY: 21.395084,
    TTD: 7.291592,
    TWD: 33.004611,
    TZS: 2536.308167,
    UAH: 39.597935,
    UGX: 3999.292573,
    USD: 1.073434,
    UYU: 41.458103,
    UZS: 12257.025434,
    VES: 27.8885,
    VND: 25175.406173,
    VUV: 127.597411,
    WST: 2.923187,
    XAF: 655.70063,
    XAG: 0.047496,
    XAU: 0.001426,
    XCD: 2.898251,
    XDR: 0.803995,
    XOF: 655.70072,
    XPD: 0.001672,
    XPF: 119.286005,
    XPT: 0.00143,
    YER: 268.484001,
    ZAR: 21.260344,
    ZMW: 20.749298,
    ZWL: 345.324005,
  },
  getCountry: () => {
    var listSymbol = symbolCurrency;
    var listCountry = _countries.countries.country;
    var list = [];
    listCountry.forEach(e => {
      var item = {};
      var symbol = listSymbol.filter(function (element) {
        return element['abbreviation'] == e['currencyCode'];
      });
      // console.log(symbol);
      item['countryName'] = e['countryName'];
      item['currencyCode'] = e['currencyCode'];
      if (symbol.length > 0) {
        item['symbol'] = symbol[0]['symbol'];
      } else {
        item['symbol'] = '';
      }

      if (item['symbol'] == null) item['symbol'] = '';
      list.push(item);
    });

    return list;
  },
  getSymbolCurrency: () => {
    return symbolCurrency;
  },
};
export default EXCHANGE;
